# Generated by Django 3.2.3 on 2021-05-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_review_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
